### ISSUE TITLE
サーバの追加でチャンネル取得失敗エラー

### ISSUE THREAD

**Issue by ntsklab** [sugtao4423/ChinachuClient#1]
アドレスとID/Pass入れた状態で保存を行うと数秒「チャンネルリストの取得中」となり、トースト通知でチャンネル取得に失敗した旨が表示されます。ChinachuのWUIのログではprograms.jsonの取得は200 OKだったのでクライアント側に問題があると考えissue投げさせていただきました。
ログが見れない環境なので完全なる推測なのですが、番組表のうちいくつかの番組のジャンルがundefinedとなっていて灰色で表示されているのでその辺でエラーが発生しているのかもと考えています。
Chinachu側若しくは環境の問題とは思いますが、もしこれが原因のようであればChinachu WUIのようにとりあえず取得して動くようになればと思います。

環境
Chinachu+Mirakurun+Rivarun/x86_64 Debian 8.5
HTL22/Android4.4.2

![ss](https://cloud.githubusercontent.com/assets/925553/16583550/41379a58-42f1-11e6-9267-5bcd9e76dfa8.png)

**Comment by sugtao4423** [comment]
issueありがとうございます。
こちらの実装としては、1週間分全ての番組を取得してチャンネルリストを作成しています。
そちらの抜けているチャンネルというのは、1週間分全ての番組が抜けているのでしょうか。
そして、何らかの方法でprograms.jsonを送っていただくことは可能でしょうか。

お手数お掛け致しますがよろしくお願い致します。

**Comment by ntsklab** [comment]
こんばんは。
チャンネルが抜けている様に見えるのはNHKのサブチャンネルの試験放送部分なので問題はないと考えています…。
jsonを見たところ、一部の番組でcategoryが欠落しているようです。。
TwitterのDMでファイル送らせていただきます。

**Comment by sugtao4423** [comment]
programs.jsonのご提供ありがとうございました。
問題を解消したものを[Google Play](https://play.google.com/store/apps/details?id=com.tao.chinachuclient)に公開しておきました。
また何かありましたらissueでもDMでも飛ばしてください。
issueありがとうございました！
（Closeしていいのかな・・・？）

**Comment by ntsklab** [comment]
サーバの追加できました！対応ありがとうございました！
