### ISSUE TITLE
Chinachu γで番組表・録画済みが取得エラーになる

### ISSUE THREAD

**Issue by nidixx** [sugtao4423/ChinachuClient#2]
Chinachu Beta・Mirakurun 環境にて正常動作していましたが
Chinachu γ にアップデート後、番組表と録画済みが番組取得エラーになってしまいました。
γでJSON構造体に一部変更があった影響かもしれません。

**Comment by sugtao4423** [comment]
返信遅れて申し訳ありません。
ちょうど5日くらい前にγで使ってみたのですが、特にエラーは見られませんでした。
ChinachuClient自体のデータ削除、もしくはサーバー削除をして再度追加してみてください。

**Comment by sugtao4423** [comment]
JSONデータのご提供ありがとうございました。
Play Storeにて公開致しました。
またなにかあればissueお願い致します。
